In [1]:
import pandas as pd

df = pd.read_excel(
    "../company_dataset/Restaurant_Sales_Sample_Data.xlsx"
)

print(df.shape)
print(df.info())

df.to_csv(
    "../cleaned_data/restaurant_sales.csv",
    index=False
)

print("Dataset Saved Successfully")

(45807, 22)
<class 'pandas.DataFrame'>
RangeIndex: 45807 entries, 0 to 45806
Data columns (total 22 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            45807 non-null  object
 1   Day_of_Week     45807 non-null  str
 2   Month           45807 non-null  int64
 3   Month_Name      45807 non-null  str
 4   Year            45807 non-null  int64
 5   Quarter         45807 non-null  str
 6   Meal_Period     45807 non-null  str
 7   Category        45807 non-null  str
 8   Item_Name       45807 non-null  str
 9   Quantity        45807 non-null  int64
 10  Unit_Price      45807 non-null  float64
 11  Gross_Sales     45807 non-null  float64
 12  Discount_Amt    45807 non-null  float64
 13  Net_Sales       45807 non-null  float64
 14  Tax_Amt         45807 non-null  float64
 15  Total_Billed    45807 non-null  float64
 16  Payment_Method  45807 non-null  str
 17  Table_No        45807 non-null  int64
 18  Server_ID       45807 non-null  str
 19  Weather         45807 non-null  str
 20  Is_Holiday      45807 non-null  int64
 21  Is_Weekend      45807 non-null  int64
dtypes: float64(6), int64(6), object(1), str(9)
memory usage: 10.2+ MB
None
Dataset Saved Successfully

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45807 entries, 0 to 45806
Data columns (total 22 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            45807 non-null  object
 1   Day_of_Week     45807 non-null  str
 2   Month           45807 non-null  int64
 3   Month_Name      45807 non-null  str
 4   Year            45807 non-null  int64
 5   Quarter         45807 non-null  str
 6   Meal_Period     45807 non-null  str
 7   Category        45807 non-null  str
 8   Item_Name       45807 non-null  str
 9   Quantity        45807 non-null  int64
 10  Unit_Price      45807 non-null  float64
 11  Gross_Sales     45807 non-null  float64
 12  Discount_Amt    45807 non-null  float64
 13  Net_Sales       45807 non-null  float64
 14  Tax_Amt         45807 non-null  float64
 15  Total_Billed    45807 non-null  float64
 16  Payment_Method  45807 non-null  str
 17  Table_No        45807 non-null  int64
 18  Server_ID       45807 non-null  str
 19  Weather         45807 non-null  str
 20  Is_Holiday      45807 non-null  int64
 21  Is_Weekend      45807 non-null  int64
dtypes: float64(6), int64(6), object(1), str(9)
memory usage: 10.2+ MB

In [3]:
df.describe()

,Month,Year,Quantity,Unit_Price,Gross_Sales,Discount_Amt,Net_Sales,Tax_Amt,Total_Billed,Table_No,Is_Holiday,Is_Weekend
count,45807.000000,45807.000000,45807.000000,45807.000000,45807.000000,45807.000000,45807.000000,45807.000000,45807.000000,45807.000000,45807.000000,45807.000000
mean,6.923090,2024.500251,1.418888,10.197432,14.468925,0.204014,14.266951,0.713348,14.980312,10.447617,0.019102,0.380007
std,3.448026,0.500005,0.617363,6.165031,11.454704,0.582106,11.304708,0.565237,11.869983,5.781078,0.136885,0.485394
min,1.000000,2024.000000,1.000000,2.900000,2.900000,0.000000,2.610000,0.130500,2.740500,1.000000,0.000000,0.000000
25%,4.000000,2024.000000,1.000000,5.810000,6.820000,0.000000,6.530000,0.326500,6.856500,5.000000,0.000000,0.000000
50%,7.000000,2025.000000,1.000000,7.990000,10.900000,0.000000,10.770000,0.538500,11.308500,10.000000,0.000000,0.000000
75%,10.000000,2025.000000,2.000000,13.340000,17.910000,0.000000,17.760000,0.888000,18.648000,15.000000,0.000000,1.000000
max,12.000000,2025.000000,3.000000,25.740000,77.220000,7.680000,77.220000,3.861000,81.081000,20.000000,1.000000,1.000000

In [4]:
df.isnull().sum()

Date              0
Day_of_Week       0
Month             0
Month_Name        0
Year              0
Quarter           0
Meal_Period       0
Category          0
Item_Name         0
Quantity          0
Unit_Price        0
Gross_Sales       0
Discount_Amt      0
Net_Sales         0
Tax_Amt           0
Total_Billed      0
Payment_Method    0
Table_No          0
Server_ID         0
Weather           0
Is_Holiday        0
Is_Weekend        0
dtype: int64

In [5]:
print("Duplicates:", df.duplicated().sum())

df = df.drop_duplicates()

print("After Cleaning:", df.shape)

Duplicates: 1
After Cleaning: (45806, 22)

In [ ]:
df["Date"] = pd.to_datetime(df["Date"])

df.info()

In [7]:
for date in df["Date"]:
    try:
        pd.to_datetime(date)
    except Exception:
        print(date)

29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025
29-02-2025

In [8]:
df["Date"] = pd.to_datetime(
    df["Date"],
    dayfirst=True,
    errors="coerce"
)

In [9]:
df["Date"].isnull().sum()

np.int64(38)

In [10]:
df["Day"] = df["Date"].dt.day

df["Week"] = df["Date"].dt.isocalendar().week

df["YearMonth"] = df["Date"].dt.strftime("%Y-%m")

In [11]:
df.head()

,Date,Day_of_Week,Month,Month_Name,Year,Quarter,Meal_Period,Category,Item_Name,Quantity,...,Total_Billed,Payment_Method,Table_No,Server_ID,Weather,Is_Holiday,Is_Weekend,Day,Week,YearMonth
0,2024-01-01,Sunday,1,Jan,2024,Q1,Lunch,Beverages,Soft Drink,1,...,3.171,Wallet,12,S01,Cloudy,0,1,1.0,1,2024-01
1,2024-01-01,Sunday,1,Jan,2024,Q1,Lunch,Starters,Soup of the Day,1,...,6.111,Cash,3,S07,Cloudy,0,1,1.0,1,2024-01
2,2024-01-01,Sunday,1,Jan,2024,Q1,Dinner,Main Course,Mushroom Risotto,1,...,18.459,Cash,2,S07,Cloudy,0,1,1.0,1,2024-01
3,2024-01-01,Sunday,1,Jan,2024,Q1,Dinner,Starters,Garlic Bread,2,...,10.185,Wallet,5,S02,Cloudy,0,1,1.0,1,2024-01
4,2024-01-01,Sunday,1,Jan,2024,Q1,Dinner,Desserts,Chocolate Lava Cake,2,...,16.842,Debit Card,19,S04,Cloudy,0,1,1.0,1,2024-01

In [12]:
df.to_csv(
    "../cleaned_data/restaurant_sales_cleaned.csv",
    index=False
)

print("Dataset Saved Successfully")

Dataset Saved Successfully

In [13]:
check_df = pd.read_csv(
    "../cleaned_data/restaurant_sales_cleaned.csv"
)

print(check_df.shape)

(45806, 25)